# Generated by Django 3.1.6 on 2021-02-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewers',
            name='id',
            field=models.CharField(max_length=180, primary_key=True, serialize=False),
        ),
    ]
