# Generated by Django 3.1.6 on 2021-02-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funapp', '0003_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
