# Generated by Django 3.1.6 on 2021-02-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funapp', '0004_auto_20210217_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image_path',
            field=models.FilePathField(),
        ),
    ]
