# Generated by Django 3.1.6 on 2021-02-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funapp', '0006_auto_20210217_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image_path',
            field=models.FileField(upload_to='media'),
        ),
    ]
