# Generated by Django 3.1.6 on 2021-02-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funapp', '0007_auto_20210217_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viewers',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='link',
        ),
    ]
