# Generated by Django 3.1.7 on 2021-02-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funapp', '0009_auto_20210219_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image_path',
            field=models.URLField(),
        ),
    ]
