# Generated by Django 3.1.7 on 2021-02-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funapp', '0010_auto_20210224_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='category_id',
            field=models.SmallIntegerField(choices=[(0, 'continue watching'), (1, 'My List'), (2, 'Romantic Movies'), (3, 'Trending Now'), (4, 'Asian TV Drama'), (5, 'Netflix Originals'), (6, 'Hindi Movies'), (7, 'Action Movies')]),
        ),
    ]
